/*
 * HnSphere.cc
 *
 * DO NOT EDIT THIS FILE!
 *
 * This file is automatically generated by obj2ptr.
 * 2010/03/09 03:27:08
 */

#include "HnSRTree/HnSphere.hh"
#include "HnSRTree/HnSphereObj.hh"

/*
 * HnSphere
 */

const HnSphere HnSphere::null;

HnSphere
new_HnSphere(const HnPoint &center, double radius)
{
    HnSphereObj *_obj;

    _obj = new HnSphereObj(center, radius);

    if ( _obj->hasConstructorFailed() ) {
        delete _obj;
        return (HnSphereObj *)NULL;
    }

    return _obj;
}

#define HnClass HnSphere
#include "HnSRTree/HnClassArray.cc"

