/*
 * HnProperties.cc
 *
 * DO NOT EDIT THIS FILE!
 *
 * This file is automatically generated by obj2ptr.
 * 2010/03/09 03:26:43
 */

#include "HnSRTree/HnProperties.hh"
#include "HnSRTree/HnPropertiesObj.hh"

/*
 * HnProperties
 */

const HnProperties HnProperties::null;

HnProperties
new_HnProperties(void)
{
    HnPropertiesObj *_obj;

    _obj = new HnPropertiesObj();

    if ( _obj->hasConstructorFailed() ) {
        delete _obj;
        return (HnPropertiesObj *)NULL;
    }

    return _obj;
}

HnProperties
new_HnProperties(const HnProperties &defaults)
{
    HnPropertiesObj *_obj;

    _obj = new HnPropertiesObj(defaults);

    if ( _obj->hasConstructorFailed() ) {
        delete _obj;
        return (HnPropertiesObj *)NULL;
    }

    return _obj;
}

#define HnClass HnProperties
#include "HnSRTree/HnClassArray.cc"

