/*
 * HnStringBuffer.cc
 *
 * DO NOT EDIT THIS FILE!
 *
 * This file is automatically generated by obj2ptr.
 * 2010/03/09 03:26:43
 */

#include "HnSRTree/HnStringBuffer.hh"
#include "HnSRTree/HnStringBufferObj.hh"

/*
 * HnStringBuffer
 */

const HnStringBuffer HnStringBuffer::null;

HnStringBuffer
new_HnStringBuffer(void)
{
    HnStringBufferObj *_obj;

    _obj = new HnStringBufferObj();

    if ( _obj->hasConstructorFailed() ) {
        delete _obj;
        return (HnStringBufferObj *)NULL;
    }

    return _obj;
}

#define HnClass HnStringBuffer
#include "HnSRTree/HnClassArray.cc"

